# Generated by Django 5.2.16 on 2026-07-20 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='A New Adventure', max_length=255)),
                ('title_es', models.CharField(default='Una Nueva Aventura', max_length=255)),
                ('child_name', models.CharField(max_length=100)),
                ('child_age', models.IntegerField(blank=True, null=True)),
                ('child_gender', models.CharField(default='boy', max_length=50)),
                ('builder_mode', models.CharField(default='child', max_length=20)),
                ('hero_animal', models.CharField(blank=True, max_length=100, null=True)),
                ('hero_job', models.CharField(blank=True, max_length=100, null=True)),
                ('hero_color', models.CharField(blank=True, max_length=100, null=True)),
                ('setting', models.CharField(blank=True, max_length=100, null=True)),
                ('companion', models.CharField(blank=True, max_length=100, null=True)),
                ('story_mood', models.CharField(blank=True, max_length=100, null=True)),
                ('magic_power', models.CharField(blank=True, max_length=100, null=True)),
                ('story_ending', models.CharField(blank=True, max_length=100, null=True)),
                ('moral', models.CharField(blank=True, max_length=100, null=True)),
                ('vocab_theme', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(default='bilingual', max_length=50)),
                ('story_length', models.CharField(default='medium', max_length=50)),
                ('encouraged_behavior', models.CharField(blank=True, max_length=255, null=True)),
                ('sidekick', models.CharField(blank=True, max_length=100, null=True)),
                ('magic_object', models.CharField(blank=True, max_length=100, null=True)),
                ('art_style', models.CharField(default='watercolor', max_length=100)),
                ('tone', models.CharField(default='whimsical', max_length=100)),
                ('grade', models.CharField(default='grade-2', max_length=50)),
                ('pronoun', models.CharField(default='he', max_length=20)),
                ('rival', models.CharField(blank=True, max_length=100, null=True)),
                ('num_pages', models.IntegerField(default=5)),
                ('reading_difficulty', models.CharField(default='medium', max_length=50)),
                ('cultural_elements', models.CharField(default='mixed', max_length=100)),
                ('bedtime_safe', models.CharField(default='yes', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('text_en', models.TextField()),
                ('text_es', models.TextField(blank=True, null=True)),
                ('illustration_prompt', models.TextField(blank=True, null=True)),
                ('dictionary', models.JSONField(blank=True, default=dict)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='api.story')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
    ]
