# Generated by Django 5.2.16 on 2026-07-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_story_storypage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storypage',
            old_name='text_es',
            new_name='text_hi',
        ),
        migrations.RemoveField(
            model_name='story',
            name='title_es',
        ),
        migrations.AddField(
            model_name='story',
            name='title_hi',
            field=models.CharField(default='एक नया रोमांच', max_length=255),
        ),
    ]
