# Generated by Django 5.2.16 on 2026-07-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_story_storypage'),
    ]

    operations = [
    ]

