# Generated by Django 5.2.16 on 2026-07-23 11:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_text_es_storypage_text_hi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(default='🏆', max_length=20)),
                ('description', models.TextField()),
                ('required_count', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent'), ('CHILD', 'Child')], default='PARENT', max_length=15),
        ),
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=7)),
                ('gender', models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl'), ('other', 'Other')], default='boy', max_length=20)),
                ('grade_level', models.CharField(default='Grade 2', max_length=50)),
                ('preferred_language', models.CharField(default='Bilingual (EN/HI)', max_length=50)),
                ('avatar', models.CharField(default='🦁', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='story',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='api.childprofile'),
        ),
        migrations.CreateModel(
            name='ReadingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(blank=True, max_length=255)),
                ('read_date', models.DateField(default=django.utils.timezone.now)),
                ('reading_time_minutes', models.IntegerField(default=15)),
                ('pages_read', models.IntegerField(default=5)),
                ('completed', models.BooleanField(default=True)),
                ('rating', models.IntegerField(default=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_logs', to='api.childprofile')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_logs', to='api.story')),
            ],
            options={
                'ordering': ['-read_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChildAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_achievements', to='api.achievement')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='api.childprofile')),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('child', 'achievement')},
            },
        ),
    ]
