# Generated by Django 5.2.16 on 2026-07-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_teacherclass_lesson_teachermessage_teacherprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
