# Generated by Django 5.2.16 on 2026-08-19 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_useractivitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherclass',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='join_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='max_students',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='school_name',
            field=models.CharField(default='Oakridge Elementary', max_length=255),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='section',
            field=models.CharField(default='A', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='subject',
            field=models.CharField(default='Reading & Literature', max_length=100),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teacherclass',
            name='academic_year',
            field=models.CharField(default='2026-2027', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherclass',
            name='grade_level',
            field=models.CharField(default='Grade 3', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherclass',
            name='name',
            field=models.CharField(default='Grade 3 — Section A', max_length=100),
        ),
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('assignment_type', models.CharField(choices=[('story', 'Story Reading'), ('quiz', 'Quiz Assessment'), ('reading_task', 'Reading Task'), ('lesson', 'Lesson'), ('activity', 'Learning Activity')], default='story', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('instructions', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('reading_level', models.CharField(default='All Levels', max_length=50)),
                ('target_all_students', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.teacherclass')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_assignments', to='api.lesson')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_assignments', to='api.quiz')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_assignments', to='api.story')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassAssignmentStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='assigned', max_length=20)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_students', to='api.classassignment')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='api.childprofile')),
            ],
            options={
                'unique_together': {('assignment', 'child')},
            },
        ),
    ]
