# Generated by Django 5.2.16 on 2026-08-19 18:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_teacherclass_options_teacherclass_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issued_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('reading_excellence', 'Reading Excellence'), ('story_explorer', 'Story Explorer'), ('quiz_champion', 'Quiz Champion'), ('reading_streak', 'Reading Streak Milestone'), ('learning_achievement', 'Learning Achievement')], default='reading_excellence', max_length=50),
        ),
        migrations.AddField(
            model_name='certificate',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='api.teacherclass'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='revoked_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('report_type', models.CharField(choices=[('progress_report', 'Student Progress Report'), ('reading_report', 'Reading Activity Report'), ('quiz_report', 'Quiz Assessment Report'), ('assignment_report', 'Assignment Performance Report')], default='progress_report', max_length=50)),
                ('period', models.CharField(choices=[('last_7_days', 'Last 7 Days'), ('last_30_days', 'Last 30 Days'), ('last_3_months', 'Last 3 Months'), ('academic_year', 'Academic Year')], default='last_30_days', max_length=30)),
                ('data_snapshot', models.JSONField(blank=True, default=dict)),
                ('teacher_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_reports', to='api.childprofile')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='api.teacherclass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
