# Generated by Django 5.2.16 on 2026-08-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_childprofile_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='classassignment',
            name='allow_late_submission',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classassignment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classassignment',
            name='teacher_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='classassignmentstudent',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='classassignmentstudent',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classassignmentstudent',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classassignmentstudent',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='classassignmentstudent',
            name='status',
            field=models.CharField(choices=[('assigned', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('late', 'Late'), ('missing', 'Missing')], default='assigned', max_length=20),
        ),
    ]
