# Generated by Django 5.2.16 on 2026-08-19 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_teacherevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSavedStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_teachers', to='api.story')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('teacher', 'story')},
            },
        ),
    ]
