# Generated by Django 4.2.30 on 2026-08-21 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_teachersavedstory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglog',
            name='read_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
