import React, { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { 
  FaMagic, 
  FaChalkboardTeacher, 
  FaUserShield, 
  FaBook, 
  FaArrowRight, 
  FaHeart,
  FaStar,
  FaRocket,
  FaPalette,
  FaGraduationCap,
  FaPlay,
  FaShieldAlt,
  FaBookOpen,
  FaChild
} from 'react-icons/fa';
import StoryBookPreview from '../../components/StoryBookPreview';
import './LandingPage.css';

export default function LandingPage() {
  const [showRoleModal, setShowRoleModal] = useState(false);
  const navigate = useNavigate();
  const [activeFeature, setActiveFeature] = useState(0);

  // Cycle through features
  useEffect(() => {
    const interval = setInterval(() => {
      setActiveFeature(prev => (prev + 1) % 4);
    }, 3000);
    return () => clearInterval(interval);
  }, []);

  const handleRoleSelect = (rolePath) => {
    setShowRoleModal(false);
    navigate(rolePath);
  };

  const features = [
    { icon: <FaMagic />, title: 'AI Story Magic', desc: 'Our AI creates personalized stories tailored to each child\'s reading level and interests.', color: 'var(--coral)', bg: 'var(--coral-light)' },
    { icon: <FaPalette />, title: 'Beautiful Illustrations', desc: 'Every story comes with unique, page-by-page watercolor illustrations generated by AI.', color: 'var(--sky)', bg: 'var(--sky-light)' },
    { icon: <FaGraduationCap />, title: 'Smart Learning', desc: 'Built-in vocabulary builder, comprehension tracking, and bilingual support (EN/ES).', color: 'var(--mint)', bg: 'var(--mint-light)' },
    { icon: <FaShieldAlt />, title: 'Safe & Trusted', desc: 'Child-safe content, parent controls, and teacher-managed classrooms with analytics.', color: 'var(--purple)', bg: 'var(--purple-light)' },
  ];

  const stats = [
    { number: '120K+', label: 'Stories Created', emoji: '📚', color: 'var(--coral)' },
    { number: '98%', label: 'Kids Love It', emoji: '❤️', color: 'var(--pink)' },
    { number: '450+', label: 'Partner Schools', emoji: '🏫', color: 'var(--sky)' },
    { number: '4.9★', label: 'Parent Rating', emoji: '⭐', color: 'var(--sunshine)' },
  ];

  return (
    <div className="landing-container">
      {/* Floating Background Decorations */}
      <div className="bg-decorations">
        <div className="bg-blob blob-1"></div>
        <div className="bg-blob blob-2"></div>
        <div className="bg-blob blob-3"></div>
        <div className="floating-emoji e1">✨</div>
        <div className="floating-emoji e2">📖</div>
        <div className="floating-emoji e3">🌟</div>
        <div className="floating-emoji e4">🎨</div>
        <div className="floating-emoji e5">🦁</div>
      </div>

      {/* Top Navigation */}
      <header className="landing-header">
        <div className="header-logo">
          <div className="logo-icon-wrap">
            <FaBookOpen />
          </div>
          <span>StoryNest</span>
        </div>
        
        <nav className="header-nav">
          <a href="#features" className="nav-link">Features</a>
          <a href="#roles" className="nav-link">For Schools</a>
          <a href="#stats" className="nav-link">Impact</a>
          <a href="#demo" className="nav-link">Demo</a>
        </nav>

        <div className="header-actions">
          <button 
            className="btn btn-ghost"
            onClick={() => setShowRoleModal(true)}
          >
            Sign in
          </button>
          <button 
            className="btn btn-primary"
            onClick={() => setShowRoleModal(true)}
          >
            Start free 🚀
          </button>
        </div>
      </header>

      {/* Hero Section */}
      <section className="hero-section animate-fade-in">
        <div className="hero-content">
          <div className="hero-badge">
            <span className="hero-badge-dot"></span>
            <span>AI-Powered Learning Platform</span>
            <FaRocket className="badge-rocket" />
          </div>

          <h1 className="hero-title">
            Every Child Deserves a
            <span className="gradient-text"> Magical Story</span>
          </h1>

          <p className="hero-subtitle">
            Create personalized, illustrated storybooks with AI. Build reading confidence, expand vocabulary, and make learning an adventure your kids will love.
          </p>

          <div className="hero-ctas">
            <Link to="/create" className="btn btn-primary btn-lg">
              <FaMagic /> Create a Story
            </Link>
            <Link to="/story/1" className="btn btn-outline btn-lg">
              <FaPlay /> Watch Demo
            </Link>
          </div>

          <div className="hero-trust">
            <div className="trust-avatars">
              <div className="trust-avatar" style={{ background: 'var(--coral-light)', color: 'var(--coral)' }}>M</div>
              <div className="trust-avatar" style={{ background: 'var(--sky-light)', color: 'var(--sky)' }}>A</div>
              <div className="trust-avatar" style={{ background: 'var(--mint-light)', color: 'var(--mint)' }}>S</div>
              <div className="trust-avatar" style={{ background: 'var(--purple-light)', color: 'var(--purple)' }}>L</div>
              <div className="trust-avatar" style={{ background: 'var(--sunshine-light)', color: '#D97706' }}>+</div>
            </div>
            <span className="trust-text">Join <strong>12,000+</strong> happy families reading together</span>
          </div>
        </div>

        <div className="hero-preview" id="demo">
          <StoryBookPreview />
        </div>
      </section>

      {/* Wavy Divider */}
      <div className="wave-divider">
        <svg viewBox="0 0 1440 80" preserveAspectRatio="none">
          <path fill="#FFF8F0" d="M0,40 C360,80 720,0 1080,40 C1260,60 1380,50 1440,40 L1440,80 L0,80 Z"></path>
        </svg>
      </div>

      {/* Stats Section */}
      <section className="stats-section" id="stats">
        <div className="stats-grid">
          {stats.map((stat, idx) => (
            <div key={idx} className="stat-bubble" style={{ animationDelay: `${idx * 0.15}s` }}>
              <span className="stat-emoji">{stat.emoji}</span>
              <span className="stat-number" style={{ color: stat.color }}>{stat.number}</span>
              <span className="stat-label">{stat.label}</span>
            </div>
          ))}
        </div>
      </section>

      {/* Features Section */}
      <section className="features-section" id="features">
        <div className="section-header-centered">
          <span className="section-eyebrow">Why StoryNest?</span>
          <h2 className="section-title">Designed for Young Minds</h2>
          <p className="section-subtitle">
            Combining artificial intelligence with proven literacy research to create engaging, level-appropriate reading experiences.
          </p>
        </div>

        <div className="features-showcase">
          <div className="features-list">
            {features.map((feat, idx) => (
              <div 
                key={idx}
                className={`feature-item ${activeFeature === idx ? 'active' : ''}`}
                onClick={() => setActiveFeature(idx)}
              >
                <div 
                  className="feature-indicator"
                  style={{ backgroundColor: feat.color }}
                ></div>
                <div 
                  className="feature-icon-circle"
                  style={{ backgroundColor: feat.bg, color: feat.color }}
                >
                  {feat.icon}
                </div>
                <div className="feature-text">
                  <h3 className="feature-title">{feat.title}</h3>
                  <p className="feature-desc">{feat.desc}</p>
                </div>
              </div>
            ))}
          </div>

          <div className="features-visual">
            <div className="feature-visual-card">
              <div 
                className="visual-icon-big animate-float"
                style={{ 
                  backgroundColor: features[activeFeature].bg, 
                  color: features[activeFeature].color 
                }}
              >
                {features[activeFeature].icon}
              </div>
              <h3 style={{ color: features[activeFeature].color }}>
                {features[activeFeature].title}
              </h3>
              <p>{features[activeFeature].desc}</p>
              <div className="visual-sparkles">
                <span className="sparkle s1">✨</span>
                <span className="sparkle s2">🌟</span>
                <span className="sparkle s3">⭐</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Role Selection Section */}
      <section className="roles-section" id="roles">
        <div className="section-header-centered">
          <span className="section-eyebrow">Choose Your Path</span>
          <h2 className="section-title">Built for Everyone in the Nest</h2>
          <p className="section-subtitle">
            Tailored dashboards and tools for administrators, educators, parents, and young readers.
          </p>
        </div>

        <div className="roles-grid">
          {/* Admin */}
          <div className="role-card role-card-coral" onClick={() => navigate('/admin')}>
            <div className="role-card-shine"></div>
            <div className="role-emoji-badge">🛡️</div>
            <h3 className="role-title">School Administrator</h3>
            <p className="role-desc">Manage school accounts, track reading benchmarks across grades, and generate performance reports.</p>
            <ul className="role-features-list">
              <li>✓ School-wide analytics</li>
              <li>✓ Teacher & student management</li>
              <li>✓ Export PDF reports</li>
            </ul>
            <span className="role-action-link">Open Admin Dashboard <FaArrowRight /></span>
          </div>

          {/* Teacher */}
          <div className="role-card role-card-sky" onClick={() => navigate('/teacher')}>
            <div className="role-card-shine"></div>
            <div className="role-emoji-badge">👩‍🏫</div>
            <h3 className="role-title">Classroom Teacher</h3>
            <p className="role-desc">Assign personalized stories, track student comprehension, and manage reading groups effortlessly.</p>
            <ul className="role-features-list">
              <li>✓ Class reading assignments</li>
              <li>✓ Vocabulary & comprehension tracking</li>
              <li>✓ Individual student progress</li>
            </ul>
            <span className="role-action-link" style={{ color: 'var(--sky)' }}>Open Teacher Portal <FaArrowRight /></span>
          </div>

          {/* Parent */}
          <div className="role-card role-card-purple" onClick={() => navigate('/parent')}>
            <div className="role-card-shine"></div>
            <div className="role-emoji-badge">👨‍👩‍👧</div>
            <h3 className="role-title">Parent & Family</h3>
            <p className="role-desc">Create custom bed-time stories with your child as the main character. Track reading logs together!</p>
            <ul className="role-features-list">
              <li>✓ Bedtime story generator</li>
              <li>✓ Family reading log</li>
              <li>✓ Custom character creation</li>
            </ul>
            <span className="role-action-link" style={{ color: 'var(--purple)' }}>Open Parent Dashboard <FaArrowRight /></span>
          </div>

          {/* Story Creator */}
          <div className="role-card role-card-gradient" onClick={() => navigate('/create')}>
            <div className="role-card-shine"></div>
            <div className="role-emoji-badge">✨</div>
            <h3 className="role-title">AI Story Creator</h3>
            <p className="role-desc">Unleash imagination! Generate a brand new illustrated story with AI in under 30 seconds.</p>
            <ul className="role-features-list">
              <li>✓ Instant AI story generation</li>
              <li>✓ Custom themes & morals</li>
              <li>✓ Interactive illustrations</li>
            </ul>
            <span className="role-action-link" style={{ color: 'var(--orange)' }}>Create Story Now <FaArrowRight /></span>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="cta-banner">
        <div className="cta-content">
          <div className="cta-emojis">
            <span className="cta-e1">🌟</span>
            <span className="cta-e2">📖</span>
            <span className="cta-e3">🚀</span>
          </div>
          <h2 className="cta-title">Ready to Start Your Storytelling Journey?</h2>
          <p className="cta-subtitle">Join thousands of educators and parents creating magical learning experiences today.</p>
          <button 
            className="btn btn-primary cta-main-btn"
            onClick={() => setShowRoleModal(true)}
          >
            <FaMagic /> Get Started Free
          </button>
        </div>
      </section>

      {/* Role Selector Modal */}
      {showRoleModal && (
        <div className="modal-overlay" onClick={() => setShowRoleModal(false)}>
          <div className="modal-content animate-bounce-in" onClick={e => e.stopPropagation()}>
            <div className="modal-header-emoji">🐣</div>
            <h3 className="modal-title">Welcome to StoryNest</h3>
            <p className="modal-subtitle">Choose your portal to continue</p>
            
            <div className="modal-buttons">
              <button className="modal-role-btn modal-btn-coral" onClick={() => handleRoleSelect('/admin')}>
                <span className="modal-btn-emoji">🛡️</span>
                <div className="role-btn-text">
                  <span className="role-btn-name">Administrator</span>
                  <span className="role-btn-desc">School analytics & management</span>
                </div>
                <FaArrowRight className="modal-arrow" />
              </button>

              <button className="modal-role-btn modal-btn-sky" onClick={() => handleRoleSelect('/teacher')}>
                <span className="modal-btn-emoji">👩‍🏫</span>
                <div className="role-btn-text">
                  <span className="role-btn-name">Teacher</span>
                  <span className="role-btn-desc">Classroom & student portal</span>
                </div>
                <FaArrowRight className="modal-arrow" />
              </button>

              <button className="modal-role-btn modal-btn-mint" onClick={() => handleRoleSelect('/parent')}>
                <span className="modal-btn-emoji">👨‍👩‍👧</span>
                <div className="role-btn-text">
                  <span className="role-btn-name">Parent</span>
                  <span className="role-btn-desc">Bedtime stories & progress</span>
                </div>
                <FaArrowRight className="modal-arrow" />
              </button>

              <button className="modal-role-btn modal-btn-purple" onClick={() => handleRoleSelect('/create')}>
                <span className="modal-btn-emoji">✨</span>
                <div className="role-btn-text">
                  <span className="role-btn-name">Create Story</span>
                  <span className="role-btn-desc">AI story generator</span>
                </div>
                <FaArrowRight className="modal-arrow" />
              </button>
            </div>

            <button className="btn btn-ghost close-modal-btn" onClick={() => setShowRoleModal(false)}>
              Cancel
            </button>
          </div>
        </div>
      )}

      {/* Footer */}
      <footer className="landing-footer-section">
        <div className="footer-content">
          <div className="footer-left">
            <div className="header-logo">
              <div className="logo-icon-wrap">
                <FaBookOpen />
              </div>
              <span>StoryNest</span>
            </div>
            <p className="footer-tagline">AI-powered personalized storybooks for children. Making reading an adventure for every child.</p>
          </div>
          <div className="footer-right">
            <p>© 2026 StoryNest Education Inc. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
